version: '3.8'

services:
  app:
    build: .
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/local?serverTimezone=Asia/Tokyo
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpw

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: local
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpw
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
